# Generated by Django 6.0.6 on 2026-07-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_id', models.IntegerField(unique=True)),
                ('breed_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=500)),
            ],
        ),
    ]
