# Generated by Django 6.0.6 on 2026-07-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedNinja',
            fields=[
                ('breed_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField()),
                ('image_link', models.CharField()),
                ('good_with_children', models.IntegerField()),
                ('good_with_other_dogs', models.IntegerField()),
                ('shedding', models.IntegerField()),
                ('grooming', models.IntegerField()),
                ('drooling', models.IntegerField()),
                ('coat_length', models.IntegerField()),
                ('good_with_strangers', models.IntegerField()),
                ('playfulness', models.IntegerField()),
                ('protectiveness', models.IntegerField()),
                ('trainability', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('barking', models.IntegerField()),
                ('min_life_expectancy', models.IntegerField()),
                ('max_life_expectancy', models.IntegerField()),
                ('max_height_male', models.IntegerField()),
                ('max_height_female', models.IntegerField()),
                ('max_weight_male', models.IntegerField()),
                ('max_weight_female', models.IntegerField()),
                ('min_height_male', models.IntegerField()),
                ('min_height_female', models.IntegerField()),
                ('min_weight_male', models.IntegerField()),
                ('min_weight_female', models.IntegerField()),
            ],
        ),
    ]
