# Generated by Django 6.0.6 on 2026-08-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0002_breedninja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedninja',
            name='max_height_female',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='breedninja',
            name='max_height_male',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='breedninja',
            name='max_life_expectancy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='breedninja',
            name='max_weight_female',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='breedninja',
            name='max_weight_male',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='breedninja',
            name='min_height_female',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='breedninja',
            name='min_height_male',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='breedninja',
            name='min_life_expectancy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='breedninja',
            name='min_weight_female',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='breedninja',
            name='min_weight_male',
            field=models.FloatField(),
        ),
    ]
